### ISSUE TITLE
Broken TS types for composeView

### ISSUE THREAD

**Issue by designcode** [InboxSDK/InboxSDK#1002]
**Describe the bug**

At the moment, on the npm package, the types for `composeView.on` method are broken for following events

- `fromContactChanged`
- `recipientsChanged`

Can you please fix it?

**Comment by wegry** [comment]
Thanks for the report. @designcode, mind giving the types in #1004 a try in your project?

**Comment by wegry** [comment]
@designcode installing `@inboxsdk/core@1.2.8-0` should let you try the newer types out.

**Comment by designcode** [comment]
@wegry That seems to have fixed the problem. Thanks a lot for quick fix 🙏
