### ISSUE TITLE
Bug:  registerThreadButton not showing tooltip on thread row hover

### ISSUE THREAD

**Issue by mohsinaliryk** [InboxSDK/InboxSDK#1014]
Hi there, 

I've registered a Toolbar Button with title. But this title is not showing as tooltip when hover over thread row in threads list. I've inspected the DOM and found that it needs to add data-tooltip attribute set to title

**Comment by aleemstreak** [comment]
Thanks we’ll prioritize this as soon as we can but a PR for this would get
merged pretty quickly.

**Comment by mohsinaliryk** [comment]
I've implemented the change and created PR for this update.

**Comment by wegry** [comment]
Closed by #1015 and released as part of `@inboxsdk/core@2.0.1`.
