### ISSUE TITLE
Bug: `addSidebarContentPanel()` parameter type changed in `2.1.2`

### ISSUE THREAD

**Issue by sybers** [InboxSDK/InboxSDK#1030]
When updating from `2.2.1` to `2.1.2` the argument type of `addSidebarContentPanel(descriptor)` changed from `ContentPanelDescriptor` to `Observable<ContentPanelDescriptor, unknown>`.

I expected this type not to change, especially within a patch update.

Is this intended? If yes, how should we do now? (perhaps the docs should be updated as well).

Thank you!

**Comment by wegry** [comment]
@sybers thanks for the report.

The changes in 2.1.2 were type only, there should be no runtime changes. 

That said, we have a number of spots in the API that take `T | Observable<T, unknown>`. `addSidebarContentPanel(descriptor)` probably needs updated to reflect that.
