### ISSUE TITLE
Bug: registerThreadRowViewHandler not triggered

### ISSUE THREAD

**Issue by Alex-Chopard** [InboxSDK/InboxSDK#1042]
**Describe the bug**
`inboxSDK.Lists.registerThreadRowViewHandler` callback isn't anymore called if the list is loaded from a search.
The issue seams to be recent and to only apply on **GSuite** account (for now).

(`inboxSDK.Conversations.registerThreadViewHandler` has also the same issue if the split panel mode is enabled)
**To Reproduce**

1. Load the extension [thread-rows](https://github.com/InboxSDK/InboxSDK/tree/main/examples/thread-rows)
2. Use a GSuite account
3. On `#inbox` everything works well
4. After a search (e.g. `#search/foo`) the `registerThreadRowViewHandler` callback isn't called anymore

**Expected behavior**
Registered callback should be called even with a search.

**Screenshots**
Without search (`#label/test`)
![Screenshot 2023-10-05 at 18 11 31](https://github.com/InboxSDK/InboxSDK/assets/29271954/87bf3ca2-950c-4a43-8f60-eb9d949bbbcb)

With a search (`#search/label:test google`)
![Screenshot 2023-10-05 at 18 11 56](https://github.com/InboxSDK/InboxSDK/assets/29271954/f4e5b62d-4889-4546-915e-6fdb345fe219)

**Comment by Alex-Chopard** [comment]
It seams to be a `querySelector` that is triggered too soon (this one: https://github.com/InboxSDK/InboxSDK/blob/main/src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts#L302)
When the code is executed, I have an empty array, but I have one item in the list. And if I manually call the selector in the console I have the row.
I hope it will help

**Comment by hubertlepicki** [comment]
I opened a related bug report, and I just checked: the same users that are reporting problems described in #1041 are also having problems with threadRowViewHandler and in both cases it seems to be that the handler fires too soon - before the relevant HTML is loaded.

**Comment by aleemstreak** [comment]
Thanks @Alex-Chopard and @hubertlepicki for the bug reports. 

We're looking into the telemetry to see if we can track how widespread this is. We may need to have an account that has this change to fix it or we might be able to fix it straight from the telemetry.

**Comment by hubertlepicki** [comment]
@aleemstreak thank you so much. We have dozens of testing accounts and will observe, as of today I can't replicate the issue on any of them but I could grant you access to one when this happens

**Comment by aleemstreak** [comment]
We have an account exhibiting this behaviour now and we're working on a fix. Should have something ready by tomorrow.

**Comment by hubertlepicki** [comment]
@aleemstreak this particular issue seems to be resolved, but we may have a couple of more issues related to these types of accounts that received the update causing the above bug.

Do you maybe know how can I get an account that exhibits such behavior? I assume it's some sort of Gmail update that it got? or maybe it's a setting I can toggle on one of existing GMail accounts to get this behavior?

It's super frustrating, we have about 70 users, who this behavior enabled, and no way to debug.

What I suspect is happening now is that the handleAllRoutes callback may be having an extra call, 2s after the original one, but it's super hard to debug it or confirm without having an access to such account.

Much appreciated any hints on how could I reproduce it

**Comment by hubertlepicki** [comment]
@aleemstreak if it's not possible to "turn on" such a feature or get an account like that for me, would it be possible to arrange some sort of "lease" of it so I can debug/see what's going on? I would report back in details my findings and/or submit a PR fix.

**Comment by aleemstreak** [comment]
It'd be most useful to have bug reports of what your users are experiencing and we can see if we can replicate.
