### ISSUE TITLE
`Conversations.registerThreadViewHandler` not triggered with split pane enabled

### ISSUE THREAD

**Issue by Alex-Chopard** [InboxSDK/InboxSDK#1071]
Hi, I've found another bug that seems related to a Gmail update, but, not all account are impacted by it.

**Describe the bug**
`inboxSDK.Conversations.registerThreadViewHandler` callback isn't called if the split pane mode is on and the list is loaded from a search.

This bug is similar to: https://github.com/InboxSDK/InboxSDK/issues/1042

**To Reproduce**

1. Have an affected account
2. Load the extension [thread-test](https://github.com/InboxSDK/InboxSDK/tree/main/examples/thread-test)
3. Enabled the split pane mode
4. On `#inbox` everything works well
5. After a search (e.g. #search/foo) the `registerThreadViewHandler` callback isn't called anymore

**Expected behavior**
Registered callback should be called.

**Screenshots**
Without a search (#label/test), the [log](https://github.com/InboxSDK/InboxSDK/blob/main/examples/thread-test/content.js#L47C10-L47C10) `threadView` appear in the console
![Screenshot 2023-11-16 at 11 53 19](https://github.com/InboxSDK/InboxSDK/assets/29271954/590ecbfb-ec40-45fe-81f8-8f32dfedf0ad)

With a search (#search/label:test google)), the [log](https://github.com/InboxSDK/InboxSDK/blob/main/examples/thread-test/content.js#L47C10-L47C10) `threadView` does not appear in the console
![Screenshot 2023-11-16 at 11 56 31](https://github.com/InboxSDK/InboxSDK/assets/29271954/7d009330-5507-4f3e-8101-d745487045b9)

**Add any other context about the problem here if anything**
I've look a bit in the code to try to find where and why that bug appear, and it's seems due to a selector that is called too early. When I have the bug, this [selector](https://github.com/InboxSDK/InboxSDK/blob/main/src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts#L346) return null.

**Comment by wegry** [comment]
> I've look a bit in the code to try to find where and why that bug appear, and it's seems due to a selector that is called too early. When I have the bug, this [selector](https://github.com/InboxSDK/InboxSDK/blob/main/src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts#L346) return null.

@Alex-Chopard It looks like you own an account that can repro that selector failure. Does the selector appear later?

**Comment by Alex-Chopard** [comment]
Yes, if I call the selector directly in the console later, the div is well find.

**Comment by Alex-Chopard** [comment]
@wegry If you need I can give the credentials of an account that has the same issue, just let me know how.

**Comment by wegry** [comment]
@Alex-Chopard that'd be lovely. You can send the credentials to z ach [at] streak.com without the space.

**Comment by wegry** [comment]
@Alex-Chopard We were unable to repro with that account.

Maybe Gmail is rolling out the change to specific regions? One of our devs tried from Canada and I tried from the US.

**Comment by wegry** [comment]
#1073 (released in `@inboxsdk/core@2.1.15`) might help with this issue.

**Comment by RBische** [comment]
Hi, unfortunately, it does not help.
We are still able to repro on this account in lists.
It happens directly after doing a search in the omnibox. It works in the inbox

**Comment by wegry** [comment]
Ok, I can repro with that account and on my own now. Will dig in.

**Comment by RBische** [comment]
Unfortunately, we just tried with the latest version (including #1075) and it still doesn't work

**Comment by wegry** [comment]
@RBische thanks for the video, that clears up a number of points for me.

It points to [a different error](https://github.com/InboxSDK/InboxSDK/blob/f9baa3ec6bd7fe52abf1ba2c3859300ee1a8dc77/src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts#L660) than we'd been seeing across reports yesterday.

Our selector logic in #1073/#1075 might need a bit more work in that portion of the code.

**Comment by Alex-Chopard** [comment]
I can confirm that `@inboxsdk/core@2.1.19` has fix this issue, I'm closing it.
Thanks for the release 🙏
