### ISSUE TITLE
`Compose.registerComposeViewHandler` Registered Compose View Handler does not fire on Reply/Reply All/Forward

### ISSUE THREAD

**Issue by emilebourquin** [InboxSDK/InboxSDK#1078]
This is probably related to the Gmail changes that occurred yesterday, as this behavior started yesterday as well, in a small number of Gmail accounts. We are running the latest InboxSDK 2.1.15

Our extension "pops-out" Compose, Reply, Reply-All, and Forwards. On a small number of Gmail accounts, the Reply/Reply All/Forward threads no longer auto-pop-out. Compose does still auto-pop-out.

I can see that the Registered Compose View Handler does not fire on Reply/Reply All/Forward, so I'm guessing the selector is incorrect.

Below are two images of Chrome Dev Tools searching for .a98.iY . The selector is found in both working and non-working, but the surrounding DOM elements are quite different between the two:

**Works properly:**
![EmileWorks a98 iY](https://github.com/InboxSDK/InboxSDK/assets/89332/96c629af-8335-44b6-b3a9-e079597a3491)

**Does not work:**
![TimDoesNotWork a98 iY](https://github.com/InboxSDK/InboxSDK/assets/89332/f2273a1d-1e63-416a-a656-115395811c66)

Hacking on this a bit, it seems the selector in the Not Working scenario should be '.nH.UG.id:has(.a98.iY)' instead of '.nH.g.id:has(.a98.iY)' , but I still can't get the Compose View Handler to fire.

**Comment by wegry** [comment]
Hey @emilebourquin, thanks for the report.

Mind creating a minimal repro extension? Our https://github.com/InboxSDK/InboxSDK/tree/main/examples folder might help you get started.

**Comment by emilebourquin** [comment]
Thanks @wegry, the 2.1.16 update seems to have (mostly?) fixed this issue. Occasionally, in the problem Gmail account, we're getting the "Thread container for preview pane wasn't found" error. If it happens again, I'll post some detail.

I'll also go down the road of getting a minimal extension set up to reproduce any possible issues.

**Comment by emilebourquin** [comment]
@wegry were still seeing issues intermittently where the "Thread container for preview pane wasn't found" error is thrown, and when the Reply does not auto-pop-out the ".ao8:has(.a98.iY)" selector is found three times in the DOM, so perhaps it's not specific enough?

**Comment by emilebourquin** [comment]
In the Gmail account that is not working properly (uses the .ao8:has(.a98.iY) part of the selector_2023_11_16) , the first message selected works properly to auto-pop-out (i.e. the registered Compose View Handler is called), but then any subsequent messages will not auto-pop-out (i.e. the registered Compose View Handler is no longer called).

Here is the initial state of the selected DOM item when the first message is selected in the preview pane:
![InitialSelect](https://github.com/InboxSDK/InboxSDK/assets/89332/6c2407a2-79ce-4edc-9acd-eec0cd1ac7a1)

And here is the state of that selected DOM item after the next message is selected in the preview pane:
![SecondSelect](https://github.com/InboxSDK/InboxSDK/assets/89332/f3806a4b-0f2d-4df7-8b0c-514819302cce)

The order of the "UG id" switches to "id UG" in the .nH.ao9 div . Is it possible that the DOM is changing underneath the previewPaneContainer.querySelector(selector_2023_11_16) , and is no longer recognized?

**Comment by emilebourquin** [comment]
Re: setting up a "minimal repro extension", all I had to do was use the thread-test example, and add:

`  sdk.Compose.registerComposeViewHandler(async (composeView) => {
    console.log('In Registered Compose View Handler');
  });`

to the `InboxSDK.load ...`

Choosing any message in the preview pane, and clicking Reply showed "In Registered Compose View Handler" in the console log. After choosing any other message and clicking Reply, "In Registered Compose View Handler" no longer showed up in the console log. The registered Compose View Handler is no longer called after any message is selected, after the first.

**Comment by emilebourquin** [comment]
@wegry I followed the steps above, using InboxSDK 2.1.17 , and I see the monkey button after viewing a thread from the search results, so we're not experiencing the #1071 issue.

Not sure if an issue, but for each time I click Reply, I get an "Error: Not implemented for inline compose views" error from line 6553 of inboxsdk.js: `if (this.#isInlineReplyForm) throw new Error('Not implemented for inline compose views');` in the extension error log.

Note that this issue, Compose View Handler does not fire after second message is selected, still exists in InboxSDK 2.1.17

**Comment by wegry** [comment]
> Note that this issue, Compose View Handler does not fire after second message is selected, still exists in InboxSDK 2.1.17

That's unfortunate.

Thanks for taking a look.

> Not sure if an issue, but for each time I click Reply, I get an "Error: Not implemented for inline compose views" error from line 6553 of inboxsdk.js: if (this.#isInlineReplyForm) throw new Error('Not implemented for inline compose views'); in the extension error log.

The call to `ComposeView.prototype.setFullscreen` in the example extension is triggering this.

```diff
diff --git a/examples/compose-tooltip-button/content.js b/examples/compose-tooltip-button/content.js
index 3475129f..cf7bb96a 100644
--- a/examples/compose-tooltip-button/content.js
+++ b/examples/compose-tooltip-button/content.js
@@ -18,7 +18,7 @@ InboxSDK.load(2, 'simple-example').then(function (inboxSDK) {
       section: 'TRAY_LEFT',
     });

-    composeView.setFullscreen(true);
+    // composeView.setFullscreen(true);

     // From https://stackoverflow.com/a/34670057/1924257
     composeView.attachFiles([
```

**Comment by wegry** [comment]
@emilebourquin we have two candidate fixes that might help with this issue. #1086 and #1087. If you could try either or both to see if they help, we'd appreciate it.

**Comment by emilebourquin** [comment]
@wegry using my `sdk.Compose.registerComposeViewHandler(async (composeView) => { console.log('In Registered Compose View Handler'); });` method in the thread-test example, the changes in main/handle-thread-view-async-render / #1086 did not fix the issue, but the changes in Alex-Chopard:fixPreviewPane / #1087 did fix the problem, i.e. "In Registered Compose View Handler" showed up in the console log every time I chose a new message, and clicked Reply.
