### ISSUE TITLE
`Toolbars.registerThreadButton` is not adding buttons to the from last three days.

### ISSUE THREAD

**Issue by vaibhav127** [InboxSDK/InboxSDK#1080]
I have developed a Chrome extension that relies on InboxSDK, which has been functioning correctly for approximately 3-4 months. However, in the past 2-3 days, I've encountered an issue where the extension does not display any buttons in the conversation or thread view toolbar, as it should when using registerThreadButton.

Screenshots:

Previous Functionality (when everything was working fine):

![image](https://github.com/InboxSDK/InboxSDK/assets/115708020/bb6475b7-6357-43e9-9926-9f9403c48a66)

Current Issue (buttons missing):

![image](https://github.com/InboxSDK/InboxSDK/assets/115708020/0a652393-e317-456a-9a5b-4b60cfa51086)
this is now

Additionally, some newer features that were added to the conversation thread are also missing.

Interestingly, on the list view, all buttons are visible on each mail.

I am unsure if others are experiencing this issue. Any assistance or insights into what might be causing this problem would be greatly appreciated.

**Comment by vaibhav127** [comment]
on one id its working and on another id it is not i don't understand why ?

**Comment by officialsuyogdixit** [comment]
Yes latest gmail update broke inboxsdk!

**Comment by wegry** [comment]
Thanks for the report @vaibhav127. We have a [number of reports](https://github.com/InboxSDK/InboxSDK/issues/1072#issuecomment-1814424547) around the recent Gmail changes.

If you have access to a Gmail account that can repro that you're willing to share, we'd appreciate it.

**Comment by vaibhav127** [comment]
@wegry 
I regret to inform you that it is not possible for me to share our official Gmail account details. However, I understand the importance of resolving your concern and am willing to offer an alternative solution. If it suits you, I can provide assistance through a desktop sharing session using AnyDesk. This approach should facilitate the necessary support while maintaining the integrity of our account security.

For your information, I manage two accounts through this platform: one is associated with a U.S.-based organization, and the other is linked to an entity in London. This setup is crucial for our operations and adheres to our organizational policies.

Please let me know if this alternative method works for you or if there is any other way I can assist.

**Comment by officialsuyogdixit** [comment]
Thanks @wegry and @vaibhav127. Can we connect on Google Meet or Skype? How to DM/Email?

**Comment by kamroot** [comment]
hi - I am happy to help to resolve this issue. I can reproduce this in a few mailboxes.

**Comment by wegry** [comment]
@kamroot @officialsuyogdixit we have two candidate PRs (#1086 and #1087) that try to patch this up. Trying:

- a local build with those PRs against the extensions in `examples`
- sharing if it helps with this issue 

would be appreciated.

**Comment by kamroot** [comment]
Will try it. Let me see if I can share my experience with these PRs later today.

**Comment by wegry** [comment]
After a few folks responded elsewhere on #1087, we've merged and released it as part of `@inboxsdk/core@2.1.19`.

**Comment by vaibhav127** [comment]
@wegry Thanks a lot i will check that

**Comment by wegry** [comment]
Fixed by #1086.

**Comment by thebinod7** [comment]
I am having the same issue as @vaibhav127 . Is it resolved?

**Comment by thebinod7** [comment]
@wegry  Im using version 2

**Comment by wegry** [comment]
@thebinod7 make sure you're up to date. The current version of the SDK can be found here: https://github.com/InboxSDK/InboxSDK/releases
