### ISSUE TITLE
Bug: Opening the right panel is very slow 

### ISSUE THREAD

**Issue by cbronquillo29** [InboxSDK/InboxSDK#1088]
Our chrome extension utilizes the right panel to display details based on the selected email thread. It takes ~25 seconds to load the right panel every time a new email thread is being selected. 

Immediately before the right panel details get rendered successfully, the error below pops up. 
<img width="989" alt="Screenshot 2023-11-23 at 12 47 05 AM" src="https://github.com/InboxSDK/InboxSDK/assets/71676884/e39d5f75-dd2e-4f0e-b63f-157270fa3277">

current version: "@inboxsdk/core": "2.1.18",
Version 119.0.6045.159 (Official Build) (arm64)
macOS: Sonoma 14.1.1

**Additional information:**
- Our right panel does not load information at all when we were in a previous version  of inboxsdk (v2.0.3). This is why we bumped the version.

**Comment by wegry** [comment]
Hey @cbronquillo29, thanks for the report. Mind trying an example extension with #1086 and/or #1087 to see if either helps with your account?

**Comment by wegry** [comment]
This might be a consequence of the logging from #1079.

**Comment by cbronquillo29** [comment]
Thanks for the quick response @wegry. Our app is now working fine when using `@inboxsdk/core@2.1.19`.
