### ISSUE TITLE
Bug: Toolbars.registerThreadButton not working

### ISSUE THREAD

**Issue by thebinod7** [InboxSDK/InboxSDK#1100]
Hi,

I have a chrome extension built using InboxSDK. I have implemented a Toolbars.registerThreadButton method to inject the button inside Gmai Inbox Thread. It was working before but suddenly has stopped working. Any update on this?

Thanks!

**Comment by wegry** [comment]
Closing as dupe of #1080 based on [this comment](https://github.com/InboxSDK/InboxSDK/issues/1080#issuecomment-1847148557).
