### ISSUE TITLE
Bug: MessageAttachmentIconDescriptor onClick should be not required

### ISSUE THREAD

**Issue by amiram** [InboxSDK/InboxSDK#1160]
**Describe the bug**
In the docs, onClick field of MessageAttachmentIconDescriptor is not required.
Should be:
onClick?: boolean;
https://inboxsdk.github.io/inboxsdk-docs/conversations/#messageattachmenticondescriptor

Are you using the remote loaded SDK or bundled from NPM? if NPM, which version?
npm version 2.1.38

**Comment by wegry** [comment]
@Macil are the docs incorrect here? #1157 mentioned making this mandatory in the PR description.
