### ISSUE TITLE
Bug: waitFor timeout

### ISSUE THREAD

**Issue by Roensby** [InboxSDK/InboxSDK#1215]
**Describe the bug**
With `sdk.Lists.registerThreadRowViewHandler`, visiting SENT or custom routes will yield a waitFor timeout uncaught exception. This bug does not happen in INBOX route

**Reproduction steps**

1. Attach a thread row view handler to SENT or a custom route. 
2. Wait 60 seconds (the default timeout for the `StreamWaitFor` method)
3. Observe the error message in the Chrome console

**Expected behavior**
No uncaught exceptions thrown

**Screenshots**
Stacktrace from Chrome console:
![image](https://github.com/user-attachments/assets/a9c421c0-d189-4b65-9a9a-da33d5310146)

A new css class that matches the "Move to Inbox" toolbar button:
![image](https://github.com/user-attachments/assets/5ea6fb90-a972-48c1-a218-0e6a87ad9e70)

**Version**
NPM 2.1.62

**Add any other context about the problem here if anything**
https://github.com/InboxSDK/InboxSDK/blob/8510fe512f666f95004b3126234ca8ffa1a42623/src/platform-implementation-js/dom-driver/gmail/views/gmail-toolbar-view.ts#L426

The issue is most likely that the `_getMoveSectionElement()` method of class `GmailToolbarView` fails to find an element with the specified classes. It seems INBOX has this class, whereas SENT and custom routes do not. However, the class `.bq5` seems to be present in cases where the existing ones (`.asb, .ase, .ns, .mw`) are not for the "Move to Inbox" toolbar button.

I can confirm that adding this extra class stops the exception from being thrown. However I am unsure if the element it returns is useful.

**Comment by Roensby** [comment]
Suggested fix: https://github.com/InboxSDK/InboxSDK/pull/1216

**Comment by jfmaggie** [comment]
Hey @Roensby thanks for the bug report and fix! Sorry for the delay, we will review and test the changes shortly! Cc @Macil

**Comment by Macil** [comment]
Thanks for this bugfix!
