### ISSUE TITLE
Bug: Conflict with Simplify Gmail – need way to tell InboxSDK to ignore certain added rows

### ISSUE THREAD

**Issue by leggett** [InboxSDK/InboxSDK#1224]
**Describe the bug**
InboxSDK is assuming certain things in parsing thread rows which is leading to a LOT of errors between Simplify Gmail and other extensions that use InboxSDK. 

I think the problem is that InboxSDK is looking for messages in the inbox and is trying to parse the bundles that Simplify creates and adds. Simplify injects new rows to bundle messages with the same label into a single row. These rows resemble message rows (have some of the same classes and structure but not completely).

**Reproduction steps**

1. I'm on a Mac, using Chrome (I doubt this matters)
2. Install and enable InboxSDK's hello-world example
3. Install and enable [Simplify Gmail](https://chromewebstore.google.com/detail/simplify-gmail/pbmlfaiicoikhdbjagjbglnbfcbcojpj)
4. Put the same Gmail label on two messages in the inbox
5. Reload Gmail and look at the developer console to see many errors about "Errors in thread row parsing". Mostly it is the three errors (under screenshots) over and over and over.

**Expected behavior**

InboxSDK to skip over things that aren't actual message rows. 

**Screenshots**

<img width="851" alt="image" src="https://github.com/user-attachments/assets/47b64cb9-178b-4fbe-9fc1-d56717976261">
<img width="962" alt="image" src="https://github.com/user-attachments/assets/f074dc8c-af0d-49b1-983a-70d00b5382e9">

And eventually I see this:
<img width="951" alt="image" src="https://github.com/user-attachments/assets/a325c691-38e3-423f-9428-34f6717cdf35">

A normal message row:
![image](https://github.com/user-attachments/assets/ffbbc898-b5f8-4e1e-91ac-0e7fc144d4b8)

A bundle injected by Simplify Gmail:
![image](https://github.com/user-attachments/assets/1970f253-c166-4aca-9a9d-3ce7dd3a70f2)

**Version**
Latest version -- I installed the Hello World via NPM and ran it unmodified and had the same errors.

- hello-world, v0.1.0
- @inboxsdk/core, ^2.1.51

Are you using the remote loaded SDK or bundled from NPM? if NPM, which version?
NPM

**Add any other context about the problem here if anything**
Simplify Gmail is a popular extension that heavily modifies Gmail. I don't use InboxSDK or any other libraries but I try to play nicely with other extensions that modify Gmail. Recently, one of my customers said that Gmail crashes on him a few times a day when he is using Gmelius and Simplify Gmail. After a bit of testing and talking with the Gmelius team, I have isolated the problem to InboxSDK.

I'm happy to add a classname or something like .ignoreRow for InboxSDK to know to ignore it. But I intentionally inject rows using some of the same DOM and classnames to make it easier to match Gmail's style.

**Comment by aleemstreak** [comment]
Thanks for the really detailed bug report! We'd love to improve compatibility.

It might takes us a few weeks to get to this though. If its super urgent though, we're happy to point you in the right direction and review any PRs.

**Comment by leggett** [comment]
Thanks for looking at it. It can wait. I'm happy to try and help when you get to it.

**Comment by leggett** [comment]
Any luck looking at this?

**Comment by leggett** [comment]
Hey guys -- checking again here. Any chance you can either ignore my added rows for bundles when scanning the inbox OR give me (and others) a way to tag rows for you to ignore?

**Comment by aleemstreak** [comment]
Sorry we haven't made any progress here. 

We'll take a quick look shortly but may ask for some help depending on what we find.

**Comment by leggett** [comment]
Happy to help!

**Comment by Macil** [comment]
The InboxSDK ignores any rows that lack an `id` value. I've just now merged a change so that the InboxSDK also ignores thread rows with the `bundle` or `inboxsdk__ignore_row` classnames. We'll release this version of the InboxSDK later today. Thanks for reporting this conflict!
