### ISSUE TITLE
Question: Why do I need to register an AppID?

### ISSUE THREAD

**Issue by camaker** [InboxSDK/InboxSDK#1234]
**Question(s)**
Why do I need to register an AppID to use InboxSDK?, Is there any purpose behind it? Can you close my application from the InboxSDK backend? If my application competes with your application, will this happen?

**Comment by aleemstreak** [comment]
We primarily created the app ids so that we could reach out to developers when there were important fixes to the SDK that rolled out (like when gmail changes). We wanted to be able to proactively reach out to folks.
