### ISSUE TITLE
Bug: ComposeView. getXxRecipients not returning recipents during sending

### ISSUE THREAD

**Issue by jfmaggie** [InboxSDK/InboxSDK#726]
**Describe the bug**
We use composeView.getXxRecipients() for [email tracking view controller](https://github.com/StreakYC/MailFoo/blob/master/extensions/common/js/modules/pixelTracker/pixelTrackerOnComposeViewController.tsx#L363-L368) during sending the email, it returns empty emails list.

```
composeView.registerRequestModifier

 const allRecipients: Array<Contact> = _.uniqBy(
            composeView
              .getToRecipients()
              .concat(composeView.getCcRecipients())
              .concat(composeView.getBccRecipients()),
            contact => contact.emailAddress
          );
```

See conversation: https://streak.slack.com/archives/C02TYCR0VNV/p1643156848015400?thread_ts=1643149720.005900&cid=C02TYCR0VNV 

**To Reproduce**
Linked our call site usage from Streak repo.

**Expected behavior**
[Emails](https://github.com/StreakYC/MailFoo/blob/master/extensions/common/js/modules/pixelTracker/pixelTrackerOnComposeViewController.tsx#L273) are not empty if filled.

**Comment by wegry** [comment]
Marking as closed based on the thread over at https://groups.google.com/g/inboxsdk/c/mYbmYU-nJy4/m/raELls8vCAAJ.
