### ISSUE TITLE
sdk.Router.handleListRoute keeps returning invalid routeId

### ISSUE THREAD

**Issue by alexeacott-tech** [InboxSDK/InboxSDK#780]
I have tried all the ENUMs in NativeListRouteIDs and can't get this error to go away. I am doing this line:
`sdk.Router.handleListRoute("INBOX", (listRouteView) => {console.log(listRouteView.getParams())})`

Any suggestions?

**Comment by Macil** [comment]
It's meant to be used like `sdk.Router.handleListRoute(sdk.Router.NativeRouteIDs.INBOX, (listRouteView) => {`. We've added this example to the docs now.
