### ISSUE TITLE
Not Compitable with Chrome extension MV3

### ISSUE THREAD

**Issue by nirvparekh** [InboxSDK/InboxSDK#782]
Getting error in Gmail from content script.
`contentScript.bundle.js:54998 Error logged: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at eval (<anonymous>)
    at contentScript.bundle.js:54820 

Original error stack:
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at eval (<anonymous>)
    at chrome-extension://ipjpliddiedabogjnnnkaojcfaiccbdm/contentScript.bundle.js:54820:27 

Error logged from:
    at logError (chrome-extension://ipjpliddiedabogjnnnkaojcfaiccbdm/contentScript.bundle.js:54976:56)
    at chrome-extension://ipjpliddiedabogjnnnkaojcfaiccbdm/contentScript.bundle.js:54861:38 

Error details: {url: 'https://www.inboxsdk.com/build/platform-implementation.js', connectivityTestResults: {…}, status: undefined, response: null, message: 'Failed to load script'}`

**Comment by MalikElate** [comment]
that's unfortunate

**Comment by aleemstreak** [comment]
@MalikElate this is no longer the case, the InboxSDK now supports MV3

**Comment by mayurfefar** [comment]
@aleemstreak Can you let me know what is required for inboxSDK v2. i am getting same error

**Comment by tiagorangel2011** [comment]
Me too. Getting this:
```
Error logged: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Original error stack: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*".
```

**Comment by ramanjoshi90** [comment]
@tiagorangel2011 Did you get any solution for that? I am getting the same error no Gmail when I use the latest inbox SDK and load extension from my local machine.

**Comment by Lonolf** [comment]
We got the same error on our Beta (v130) and Canary (131) version. Updated InboxSDK to the last version.
Still working on the production channel.
Can you give us some help? Thanks!
