### ISSUE TITLE
Bug: registerThreadRowViewHandler is not fired on several Compose sendings

### ISSUE THREAD

**Issue by auchynnikau** [InboxSDK/InboxSDK#788]
**Description**
`registerThreadRowViewHandler` is not fired after quick send from several Compose after pasting message content.

This functionality is used for tracking emails using [PandaDoc email tracker extension](https://www.pandadoc.com/free-email-tracker-for-gmail/). The same problem was noticed and reproduced using another extension for tracking emails - [Streak](https://www.streak.com/). Also happens after quick send and content pasting.

Looks like an issue already [mentioned in Google Groups](https://groups.google.com/g/inboxsdk/c/AjIoOP6bJTk) might be related to this case and have similar reason but using `registerComposeViewHandler`.

**Steps to Reproduce**

1. Open Compose popup;
2. Fill all fields;
3. Open second Compose popup;
4. Paste content and quick send message;
5. Send first opened message;
6. Event is not fired on second sending.

**Expected behavior**
Event fired on each sending action.

**Screenshots**
<img width="259" alt="Screenshot 2022-10-12 at 01 00 50" src="https://user-images.githubusercontent.com/33329898/195206316-9ff4e239-258b-463e-891f-ce11e6b85b50.png">

**Comment by shff** [comment]
I can reproduce this as well.

For the second compose view, the "sent" event will be triggered prematurely, when the Draft is saved, but with the wrong ID. It won't be triggered when the email is sent.

**Comment by fjaeger** [comment]
Same here! We have this issue not being able to reliable fetch the final message-id for subsequently sent emails 😱

**Comment by wegry** [comment]
Resolved by #824.
