### ISSUE TITLE
Bug: MessageView addToolbarButton broken

### ISSUE THREAD

**Issue by ggdev3000** [InboxSDK/InboxSDK#797]
**Describe the bug**
MessageView addToolbarButton seems to not work anymore.
The function gets called without error but the toolbar button doesn't appear.

**To Reproduce**

      sdk.Conversations.registerMessageViewHandler(function(messageView) {
        messageView.addToolbarButton({
          orderHint: 0,
          title: "Test",
          section: "MORE",
          iconClass: 'text_call',
          hasDropdown: false,
          onClick: function (e) {
            alert('test')
          }
        });

**Add any other context about the problem here if anything**
It seems some changes in Gmail just before 15th of Oct 2022 caused this.

**Comment by timvdalen** [comment]
I've been able to reproduce this with both a really old version of InboxSDK (from at least 6 years ago) and the latest version for https://chrome.google.com/webstore/detail/gmail-message-id-finder/comcoiiifldaaejpbgbincdkoohihbae

**Comment by yoxel** [comment]
Multiple people reported this in the Google group: https://groups.google.com/g/inboxsdk/c/F4rlEh3prao
Any fixes anticipated?

**Comment by seilbek-yoxel** [comment]
Our clients also have this problem.
Any ideas for a fix?

**Comment by neu-tom** [comment]
Same problem here. Has anyone found a potential replacement module or a potential fix?

**Comment by JeroenCorthout** [comment]
Same here

**Comment by aleemstreak** [comment]
This is likely a new selector issue, we'll get to it in the next few weeks. Happy to merge a fix if anyone wants to investigate.

**Comment by manlymgmt-anthony** [comment]
Same problem here, eagerly awaiting a fix.

**Comment by neu-tom** [comment]
Any updates on when a fix should be expected? Would like to inform the users of my extension.

**Comment by aleemstreak** [comment]
We have this scheduled for mid december. Happy to review and PRs earlier than that though if someone wants to take a stab at it.
