### ISSUE TITLE
ComposeView.getToRecipients() doesn't work within registerRequestModifier callback

### ISSUE THREAD

**Issue by bkorobeinikov** [InboxSDK/InboxSDK#801]
**Describe the bug**
Calling `ComposeView.getToRecipients()` during `ComposeView.registerRequestModifier` callback returns empty result

**To Reproduce**

1. Start new compose
2. Register `registerRequestModifier` handler for composeView
4. add one or multiple to recipients
5. click "send" 
6. when `registerRequestModifier` is called, access `composeView.getToRecipients()`

**Expected behavior**
`ComposeView.getToRecipients()` should return recipients set in the compose `To` field 

**Add any other context about the problem here if anything**
Initial research lead to believe that during `registerRequestModifier` invocation, compose view element no longer has recipients chips, but instead has only span elements that are shown when To field is unfocused.

**Comment by wegry** [comment]
See https://github.com/InboxSDK/InboxSDK/pull/951#issuecomment-1642172398, but I cannot reproduce this issue as reported with `examples/compose-button-tooltip`.

**Comment by aleemstreak** [comment]
@bkorobeinikov have a minimal example?
