### ISSUE TITLE
Question: Is it free to use ?

### ISSUE THREAD

**Issue by MatteoGauthier** [InboxSDK/InboxSDK#810]
**Question(s)**

I wanted to know if the InboxSDK is free to use, the website landing page suggests that you have to pay something, and the use of APP_ID is confusing.

Can you enlighten me on this subject ?

**Comment by Macil** [comment]
It's free to use. We ask developers to register an app id mainly so that we have an email address we can use to contact the developer of an extension using the InboxSDK in case there's some kind of compatibility issue with the extension and Gmail or other extensions.

**Comment by MatteoGauthier** [comment]
@Macil Okay thanks a lot for your answer 👍
