### ISSUE TITLE
Bug: error while calling the ComposeView.attachFiles() method in MV2 mode

### ISSUE THREAD

**Issue by eminescu** [InboxSDK/InboxSDK#842]
Hello, I'm using your APIs in MV2 mode (with remote loading).
We've been unable to use the ComposeView.attachFiles() since a few days, the following error is returned:
```
platform-implementation.js:formatted:32877 Error logged: ReferenceError: Cannot access 'r' before initialization
    at Object._attachFiles (platform-implementation.js:formatted:40270:55)
    at Object.attachFiles (platform-implementation.js:formatted:40292:29)
    at p.attachFiles (platform-implementation.js:formatted:62371:67)
    at attachFiles (search.js:908:35)
    at Object.insertProposal (search.js:928:19) 
```
Indeed if you look at the relevanti minified code hosted on:
https://www.inboxsdk.com/build/platform-implementation.js
you can see the following (beautified):
```
            async _attachFiles(e, t) {
                this._hideDropzones();
                const n = (0,
                s.default)((()=>(0,
                S.simulateDragEnd)(this._element, e)));
                try {
                    let e = !0;
                    for (let r of a.default.partition(r, 3)) {
                 [...]
```
As you can see the minifier produce invalid code, at the 8th line it should have been ` for (let r of a.default.partition(e, 3)) {`

1. load inboxsdk in MV2 mode: `InboxSDK.load(2, 'YOUR_APP_ID_HERE').then(function(sdk){})`
2. register a composeView handler: `sdk.Compose.registerComposeViewHandler(function(composeView){})`
3. call the attachFiles method: `composeView.attachFiles()`

**Comment by aleemstreak** [comment]
Thanks for the report. We'll be able to take a look at this the 2nd week of March but happy to review any PRs before then

**Comment by kganeshv89** [comment]
Hello,
We have 10k +Enterprise users impacted by this issue. Can you please expedite this fix please ? Happy to share more info.

**Comment by Macil** [comment]
This is fixed and deployed now. Thanks @Alaanor for the PR!
