### ISSUE TITLE
When triggering composeView.popOut() an exception occurs  

### ISSUE THREAD

**Issue by uri3000** [InboxSDK/InboxSDK#850]
**Describe the bug**
When triggering popOut on a registered composeView, there is an exception which cuts out the code flow.

**To Reproduce**

1. Use this setup code on extension init to reproduce:

```javascript
useEffect(() => {
    const loadInboxSdk = async () => {
      const inboxSdk = await InboxSDK.load(2, process.env.PLASMO_PUBLIC_INBOX_SDK_APP_ID, null);
      setInboxSdk(inboxSdk);

      inboxSdk.Compose.registerComposeViewHandler(async (currentComposeView) => {
        setComposeView(currentComposeView);
        if (currentComposeView.isInlineReplyForm()) {
          await currentComposeView.popOut();
        }
      });
    }
 
    loadInboxSdk().catch(console.error);
  }, []);
```

**Expected behavior**
Compose view is opened in a popOut view without errors in the console.

**Screenshots**
<img width="747" alt="image" src="https://user-images.githubusercontent.com/7873124/221556169-ef1d529a-1b67-4a76-825d-d1b208bba610.png">

**Comment by 1TheMuffinMan** [comment]
In my opinion you'll have better luck getting an answer if you reproduce in a vanilla chrome extension. No reactjs, no bundler like webpack. At some point someone will need to run the code to troubleshot and it's possible that there's a side effect in your application that is causing this.

**Comment by wegry** [comment]
# Repro attempt 

## Steps

Tested with the following commit (1861238870f159ee766f3bc754afb4ce186ed637) and [diff](https://gist.github.com/wegry/57b854c464d5a79e89e04a8abadcdb6f).

## Video

Video of my failed-ish repro -> https://www.loom.com/share/03451f04b2044babb9b56c195aff4d62

## Logged errors

I only see errors from Gmail's JS:

```
m=a:254 Uncaught TypeError: Cannot read properties of undefined (reading 'zFye3e')
...
```

```
13:45:54.361 m=b:761 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at _.bD (m=b:761:174)
    at R5j (m=cm,mo,e,be:2231:409)
    at I5j (m=cm,mo,e,be:1764:202)
    at m=cm,mo,e,be:1758:464
    at m=cm,mo,e,be:1757:146
    at m=cm,mo,e,be:876:249
```

## Misc thoughts

These errors don't seem to "cut[] out the code flow." @uri3000 one thing to note is that this line

```
      inboxSdk.Compose.registerComposeViewHandler(async (currentComposeView) => {
```

from your example [doesn't match the interface](https://github.com/InboxSDK/InboxSDK/blob/1861238870f159ee766f3bc754afb4ce186ed637/src/inboxsdk.d.ts#L89). Handlers are expected to be synchronous.
