### ISSUE TITLE
subjectChanged event in composeView

### ISSUE THREAD

**Issue by strutt** [InboxSDK/InboxSDK#911]
Hello,

I am using InboxSDK to give our client's emails a content score. We want to incorporate the subject as well as the html content. It would be very useful to hook into a `composeView.on("subjectChanged")` event in addition to the `"bodyChanged"` event.

Looking through the code it seems like it would be simple to implement. Is this something you would be willing to support?

Thanks

Ben

**Comment by aleemstreak** [comment]
Sounds like a good idea. Would def review a PR if you made one!
ᐧ
