### ISSUE TITLE
attachFiles() method failing to add attachment to compose window opened in full screen

### ISSUE THREAD

**Issue by shashikiran-im** [InboxSDK/InboxSDK#953]
Hi InboxSDK Team,

**Issue:**
I found that attaching documents to compose window (using attachFiles() API method) opened in full screen (Opted for "Default to full screen" in compose window) is not working in latest chrome browser version (114.0.5735.199 & above).
I observed the below error message in the console while attaching document to compose window fails,
					
**ERROR IN CONSOLE:**
Error logged: Error: Failed to find dropzone
at We._findDropzoneForThisCompose (platform-implementation.js:7:52570)
at We._attachFiles (platform-implementation.js:7:53122)
					
Original error stack:
Error: Failed to find droozone
at We._findDropzoneForThisCompose (https://www.inboxsdk.com/build/platform-implementation.js:7:52570)
at We. attachFiles (https://www.inboxsdk.com/build/platfion.is:7:53122)
Error logged from:
at N (https://www.inboysok.com/builo/platform-implementation.is:23:9732)
aT M.error (https://www.inboysok.com/builo/platform-implementation.is:23:7005)
at we._attachFiles https://www.inboxsdk.com/build/platform-implementation.is:7:53244)
					
Could you let us know is this is known issue with attachFiles() API method when compose window is opened in full screen mode and if so then let us know if have any plan to fix it.
					
**NOTE:** 
1. FYI that attaching document to compose window opened in non-full screen mode is working without any issue.
2. Extension is build using MV2.

**Steps to reproduce the behavior:**
1. Add button to compose window toolbar
2. Add attachment to compose window opened in full screen mode using attachFiles() API method on click of the button.
3. Observe that it fails to add attachment to compose window with error in console (Refer above error message) 

**Expected behavior**
1. attachFiles() API method should add attachment to compose window opened in full screen mode and in non-full screen mode.

Thanks in Advance
SK

**Comment by wegry** [comment]
Thanks for the report.

I can repro with the following example extension https://github.com/InboxSDK/InboxSDK/blob/3bfd440d2b7447057c593828756f5d9d1f3ff62b/examples/compose-tooltip-button/content.js#L6

and diff

```diff
diff --git a/examples/compose-tooltip-button/content.js b/examples/compose-tooltip-button/content.js
index 7c80b0cc..71b61638 100644
--- a/examples/compose-tooltip-button/content.js
+++ b/examples/compose-tooltip-button/content.js
@@ -5,6 +5,9 @@ InboxSDK.load(2, 'simple-example').then(function(inboxSDK) {
 
 		window.composeView = composeView;
 
+    // From https://stackoverflow.com/a/34670057/1924257
+    composeView.attachFiles([new File(["teehee"], "filename", { type: 'text/html' })])
+
 		var button = composeView.addButton({
 			title: 'Monkeys!',
 			iconUrl: chrome.runtime.getURL('monkey.png'),
```

**Comment by wegry** [comment]
> Could you let us know is this is known issue with attachFiles() API method when compose window is opened in full screen mode 

It hasn't come up before to my knowledge. We do have a few other spots where fullscreen behavior is suboptimal&ndash;#727 for example.

> and if so then let us know if have any plan to fix it.

PRs welcome.

**Comment by shashikiran-im** [comment]
Thanks @wegry for reply and confirming the issue. I will try to address the issue soon.

**Comment by wegry** [comment]
Here's a longer diff that shows `ComposeView.prototype._findDropdownForThisCompose` with a bit more logging (and the same example extension).

```diff
diff --git a/examples/compose-tooltip-button/content.js b/examples/compose-tooltip-button/content.js
index 7c80b0cc..6135cc66 100644
--- a/examples/compose-tooltip-button/content.js
+++ b/examples/compose-tooltip-button/content.js
@@ -5,6 +5,10 @@ InboxSDK.load(2, 'simple-example').then(function(inboxSDK) {
 
 		window.composeView = composeView;
 
+    composeView.setFullscreen(true);
+    // From https://stackoverflow.com/a/34670057/1924257
+    composeView.attachFiles([new File(["teehee"], "filename", { type: 'text/html' })])
+
 		var button = composeView.addButton({
 			title: 'Monkeys!',
 			iconUrl: chrome.runtime.getURL('monkey.png'),
diff --git a/src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view.ts b/src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view.ts
index d032cd38..62ae2762 100644
--- a/src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view.ts
+++ b/src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view.ts
@@ -1185,31 +1185,43 @@ class GmailComposeView implements ComposeViewDriver {
     const dropzoneSelector = inline
       ? 'body > .aC7:not(.aWP)'
       : 'body > .aC7.aWP';
-    const el: HTMLElement | null | undefined = t.toArray<
-      any,
-      HTMLElement | null | undefined
-    >(
-      Array.prototype.slice.call(
-        document.querySelectorAll<HTMLElement>(dropzoneSelector)
-      ),
-      t.compose(
-        t.filter(isElementVisible),
-        t.filter((dropzone: HTMLElement) => {
-          const top = parseInt(dropzone.style.top, 10);
-          const bottom = top + parseInt(dropzone.style.height, 10);
-          const left = parseInt(dropzone.style.left, 10);
-          const right = left + parseInt(dropzone.style.width, 10);
-          return (
-            top >= rect.top &&
-            left >= rect.left &&
-            right <= rect.right &&
-            bottom <= rect.bottom
-          );
-        }),
-        t.take(1)
-      )
-    )[0];
+    const el = [
+      ...document.querySelectorAll<HTMLElement>(dropzoneSelector),
+    ].find((dropzone: HTMLElement) => {
+      if (!isElementVisible(dropzone)) {
+        return false;
+      }
 
+      const top = parseInt(dropzone.style.top, 10);
+      const bottom = top + parseInt(dropzone.style.height, 10);
+      const left = parseInt(dropzone.style.left, 10);
+      const right = left + parseInt(dropzone.style.width, 10);
+      console.log(
+        'dropzone',
+        dropzone,
+        { top, bottom, left, right },
+        'rect',
+        this._element,
+        {
+          top: rect.top,
+          bottom: rect.bottom,
+          left: rect.left,
+          right: rect.right,
+        }
+      );
+      console.table({
+        'top >= rect.top': top >= rect.top,
+        'left >= rect.left': left >= rect.left,
+        'right <= rect.right': right <= rect.right,
+        'bottom <= rect.bottom': bottom <= rect.bottom,
+      });
+      return (
+        top >= rect.top &&
+        left >= rect.left &&
+        right <= rect.right &&
+        bottom <= rect.bottom
+      );
+    });
     if (!el) {
       throw new Error('Failed to find dropzone');
     }
```

In my local testing on a 13" MacBook Pro, the logged table from the diff above is:

Check | Result
-- | --
top >= rect.top | true
left >= rect.left | true
right <= rect.right | true
bottom <= rect.bottom | false


It looks like the `bottom <= rect.bottom` check is the one that's failing in my local testing. I think I may try gating that particular check above with `ComposeView.prototype.isFullscreen()`.

**Comment by shashikiran-im** [comment]
Hi Wegry, 

Thanks for analyzing and suggesting to check whether compose window is opened in full screen mode using inboxSDK API method (ComposeView.prototype.isFullscreen()). 

FYI that after reporting the issue in GitHub I debugged it and found same reason for the cause of the issue as “bottom <= rect.bottom” is failing because there is gap b/w compose window & bottom of the Gmail page when compose window opened in full screen mode (versus compose window opened in non-full screen mode where there is no gap b/w compose window & bottom of the Gmail page). 

 I think we should compare with only “top” in case of full screen mode as below (I am yet to try), 
const bottom = ComposeView.prototype.isFullscreen()  ? top : (top + parseInt(dropzone.style.height, 10)); 

Please share your thoughts.

Thanks,
Shashikiran

**Comment by wegry** [comment]
@shashikiran-im have tried out the patch in #964 locally?
