### ISSUE TITLE
Bug: Click event stopped firing for button added to Attachment card (Regression Issue)

### ISSUE THREAD

**Issue by shashikiran-im** [InboxSDK/InboxSDK#989]
Hi InboxSDK team,

Button added to Gmail attachment card is not firing onClick event from inboxSDK version 1.2.3. But It works till inboxSDK version 1.2.2, hence it is regression issue. Refer Code snippet below,

**CODE:**
			sdk.Conversations.registerFileAttachmentCardViewHandler(card => {
			    const iconUrl = "https://example.com/foo.png";
			    const tooltip = "Open it";
			    
			        card.addButton({
			            iconUrl: iconUrl,
			            tooltip: tooltip,
			            onClick: (e) => {
			                console.log("Clicked!");  //Not getting fired from InboxSDK version 1.2.3 & above
			            }
			        });
			    });      
			});
			
**NOTE:** Couple of errors are thrown in the console on the latest inboxSDK version (1.2.3 & above)  as below, I guess this might be indirectly causing onClick event not to fire (But I didn't understand where it is breaking).
			
			ERROR-1:
			platform-implementation.js:23 Error logged: Error: Failed to find nav item
			    at yt (platform-implementation.js:79:20863)
			    at eval (platform-implementation.js:114:68275) 
			
			ERROR-2:
			Uncaught (in promise) TypeError: Cannot read properties of null (reading 'Ra')
			    at Object.CIk [as isConversationViewDisabled] (m=gm:526:178)
			    at <anonymous>:2:41138
			
I kindly request to address this regression issue.

Thanks in Advance,
Shashikiran

**Comment by wegry** [comment]
Thanks for the report @shashikiran-im. I believe #988 and #990 are the same underlying issue. #988 was merged an hour or so ago.

**Comment by shashikiran-im** [comment]
Thanks @wegry for addressing the issue and now click event is working for button added to attachment card.
