### ISSUE TITLE
Bug: AttachmentCardView.addButton() onClick handler not executed

### ISSUE THREAD

**Issue by eminescu** [InboxSDK/InboxSDK#990]
Hello, I'm using InboxSDK APIs in MV2 mode (with remote loading).

In the latest versions of InboxSDK the method AttachmentCardView.addButton() is not working correctly: the button is created but nothing happens when it is clicked.

1. register a new messageViewHandler: `sdk.Conversations.registerMessageViewHandler( messageView => { ... } )`
2. retrieve the attachment card view from a message: `let cardViews=messageView.getFileAttachmentCardViews()`
3. add a button to one of the attachments:
```
cardViews[0].addButton({
    iconUrl: ...,
    tooltip: ...,
    onClick: function(attachmentCardClickEvent){ alert(1) }
})
```
5. nothing happens when clicking the button

I created the PR #988 that shoud fix the issue.

**Comment by wegry** [comment]
@eminescu I've deployed a remote loaded release containing #988. Version `0.7.25-1692014991507-db1e0587dc1c4978` was deployed sometime after 2023-08-10T11:43:01.907Z.

For npm consumers of `@inboxsdk/core`, the fix should be available in v1.2.5.
